### ISSUE TITLE
Unvalid SMB1 rom.

### ISSUE THREAD

**Issue by yourizuring** [Coolcord/Level-Headed#13]
So I downloaded the PC10 version of the Super Mario Bros rom for full support to use in the level-header, but it's somehow unvalid. It even says .nes at the end. Why is that and can that be fixed?

**Comment by Coolcord** [comment]
Thanks for the bug report!

After a quick search online, I found another PC10 ROM which has a different iNES header than the one I added support for. One of these two headers is invalid. As a result, I've decided to add an [extra check](https://github.com/Coolcord/Level-Headed/commit/7d774476ea365d2fc70be1b42e9792e36c150080) to the ROM building code that will strip out invalid or unrecognized ROM headers.

This new fix will be included in v0.3.4 when it comes out. Until this update is ready, I'd recommend using one of the other [supported ROMs](https://github.com/Coolcord/Level-Headed/wiki/Supported-ROMs) (ideally _Super Mario Bros. (JU) (PRG0) [!].nes_ or _Super Mario Bros. (JU) (PRG1).nes_). Alternatively, you can [compile Level-Headed from source](https://github.com/Coolcord/Level-Headed/wiki/Compiling-Level%E2%80%90Headed-via-the-Unix-Build-Script) to take advantage of the fix now.
