### ISSUE TITLE
3 Hack/Enhancements Requests

### ISSUE THREAD

**Issue by stvene3004** [Coolcord/Level-Headed#18]
This one makes it so that Fire Mario power-downs to Big Mario when get hurt: https://www.romhacking.net/hacks/3570/
This other is more than a graphics hack(because it also adds new graphics), so it can't be included in the graphics pack list (believe me, I've tried): https://www.romhacking.net/hacks/5406/
The final one adds a new palette to Luigi by making him use Mario's palette while convert the orange into green(to make Luigi look like the SMB1 Deluxe (GBC) Luigi): https://www.romhacking.net/hacks/5228/

**Comment by stvene3004** [comment]
I have one more request: This adds Mario's voice from SM64: https://www.romhacking.net/hacks/5713/

**Comment by Coolcord** [comment]
https://www.romhacking.net/hacks/3570/
This one is actually already in Level-Headed. You can set it manually by creating a custom difficulty and selecting the "Revert to Super Mario after taking damage" checkbox. It's on by default in Normal difficulty.

https://www.romhacking.net/hacks/5406/
[I took the time to import this graphics pack by your request.](https://github.com/Coolcord/Level-Headed_Data/commit/59df25bc8e502d21dd5b9b6695044f49e6a7fd83) It will be included in v0.3.9.

https://www.romhacking.net/hacks/5228/
I'm going to have to say no to this one. Believe it or not, this one actually makes some pretty significant changes to the ROM's assembly, with the only real benefit being that Fire Luigi is now independently green while Fire Mario is still red. While I like the idea, it would actually be a lot of work to incorporate into Level-Headed, especially considering all 14 other custom powerups would have to be updated to accommodate this change.

While I realize that this isn't exactly what you're asking for, you can get Luigi's colors to be the same as SMB1 Deluxe by using the "SMB1 DX" Mario Sprite Palette option (though the fire state will still be red). The "Luigi's Fire Flower" powerup will use Luigi's Fire Flower colors from SMB1 Deluxe, though it does change the physics of the fireballs.

https://www.romhacking.net/hacks/5713/
I'm going to have to say no to this one as well. While it's an impressive hack, the sounds tend to cause the game to lag. This lag will only get amplified if it is incorporated into Level-Headed, especially on the higher difficulties.

Thanks for the suggestions! I apologize that I couldn't include everything.

**Comment by jaxon19** [comment]
hi
