### ISSUE TITLE
[Feature Request] Option to save/import configuration file from within the application

### ISSUE THREAD

**Issue by macobra52** [Coolcord/Level-Headed#22]
Currently the best way to share configuration settings with other players (outside of taking screenshots) is to share the **SMB1_Compliance_To_SMB1.cfg** file in the Config folder. In our testing replacing this file with one from another player's installation copied over all settings previously used by that player, which works fine but comes with inconveniences:

-All shared cfg files have to have this exact name and be manually placed in the directory
-The Output ROM location is copied over as well
-Possibly other issues/potential issues we are not aware of due to the non-standard procedure

To simplify things, a way to save and import configuration files from within Level-Headed itself would be a nice feature to have. With all of the configuration options it has (and more to come I am sure) it would make it easier to swap between different customized presets and share them with other players.

**Comment by Coolcord** [comment]
This feature has been added in v0.3.10. Thanks again for your feature request!
