### ISSUE TITLE
[Feature Request] Option to generate solid ceiling for underground levels

### ISSUE THREAD

**Issue by macobra52** [Coolcord/Level-Headed#23]
Not sure if this is doable, but worth a shot. With underground levels the ceiling uses the standard breakable bricks, which if you are at least Super Mario allows you to break through and run on the ceiling if you are able to reach that high. These allows you to essentially 'cheese' the whole level bypassing all generated obstacles/enemies.

If possible, an option to use something solid (like the ground tiles or the wall tiles that you see in the same levels) for the ceiling instead would be useful to prevent Mario from being able to reach the ceiling easily. I understand they may still be gaps generated that could potentially allow you to reach the ceiling (similar to the castle levels), but the idea is to make it a rarer possibility that what it currently is.

**Comment by Coolcord** [comment]
## Current Plans
The Castles at the end of underground and underwater levels are really just a place holder for now. Currently, the plan for underground levels is to end them with a pipe and a wall. Beyond this wall will usually just be a death pit. Players will be expected to enter the pipe to leave the level. If a player is on top of the ceiling when he reaches the end of the level, he'll have no choice but to kill himself by dropping into the pit, as the pipe will be unreachable. This will make going on top of ceilings risky, and will most likely result in a death. However, I have no plans to implement this until after v0.4.

This pipe exit level ending will also be necessary for auto scrolling levels. Currently, if a player is at the far right side of the screen when the auto scrolling stops and he hits the flagpole, a soft-lock occurs.

## Making the Ceiling Solid
In SMB1, certain elements of the level are managed by what I'd call the brick pattern generator. This functionality is built-in to SMB1's engine. To explain brick patterns in short, the SMB1 engine will infinitely generate “bricks” or blocks in a certain pattern as the player continues to move to the right. In the case of overworld levels, the brick pattern that is set is called "Surface". In the case of underground levels, this pattern is called "Surface_And_Ceiling". All available brick patterns options can be seen [here](https://github.com/Coolcord/Level-Headed/wiki/How-to-Create-Your-Own-Levels-with-the-SMB1_Compliance-Format#brick_pattern-surface).

Changing all bricks in a brick pattern would be simple, but would affect all other brick patterns in overworld and underground levels. Changing  just the ceiling section of a brick pattern to a solid block in only underground levels would likely require assembly. As it stands, I currently have no further plans to include any more assembly hacks.

If someone else wants to write this feature, I'd consider including it. However, I really need to focus my efforts towards development of v0.4 when I can get the time.

For now, I'll have to turn down this feature request. "Cheesing" the underground levels won't be possible anymore once pipe exits are implemented, but that won't happen until sometime after the level generator overhaul in v0.4. Unfortunately, I can give any ETA on if/when pipe exits will be implemented.
