### ISSUE TITLE
[Feature Request] A bunch of new difficulty settings.

### ISSUE THREAD

**Issue by OopityDoop** [Coolcord/Level-Headed#25]
The custom difficulty settings are great, but are, in my opinion, incomplete. The following settings would complete the custom difficulty settings:
Goombas Can Spawn (1-11)
Green Koopas Can Spawn (1-11)
Red Koopas Can Spawn (1-11)
Paratroopas Can Spawn (1-11)
Off-screen Bullet Bill Spawn Chance Per Level (%)
Flying Cheep Cheep Spawn Chance Per Level (%), to fine-tune difficulty progression
Earliest Bowser Flame Start Point (Level Start, Early, Halfway, Late, Final Stretch, Random)
Latest Bowser Flame Start Point (Level Start, Early, Halfway, Late, Final Stretch, Random), Bowser flames need more customizability.
Bowser Starts Throwing Hammers (1-11)
Bowser Hammer Throw Rate (Same options as Hammer Bros. Throw Rate), Some of us would really appreciate it if he wasn't so obsessed with hammers; others might think he needs to throw more, and again, difficulty progression.
Minimum 1-Ups (0-5)
Minimum 10 Coin Blocks (0-5)
Minimum Brick Block Powerups (0-5)
Minimum Question Block Powerups (0-5)
Minimum Starmen (0-5)
Question Block Powerup Spawn Chance (%), So you can make it as easy or as hard as you want to get powerups, or just have a fair shot at getting to the highest powerup in each level. If water levels really can't have blocks, they can be exempt.
Min Level Length (Same options as Max Level Length), so those who prefer longer levels can have more consistent level lengths in their random games.
More time limit options (300, 400, 500, Proportional to Level Length, Random)

Yes, I know this is a lot. If any of these wouldn't be possible to do, tell me.

**Comment by Coolcord** [comment]
Thanks for the feature request! Sorry for the late response. These would be nice settings to add. However, I'm switching focus to the level generator itself, as I don't want this project to get too bogged down by feature creep. These are good ideas though, and if you or anyone does write these, I'd be more than happy to include them into the project.
