### ISSUE TITLE
[Feature Request] Previews of sprites and music.

### ISSUE THREAD

**Issue by OopityDoop** [Coolcord/Level-Headed#26]
because how will someone who hasn't seen every custom sprite or heard every user created song beforehand know what they're choosing when generating their game?

Also, Coolcord, I would greatly appreciate it if you would reply to my posts so I at least know you read them.

**Comment by Whammaster** [comment]
I'm sure he has read them, he likes to formulate response to fully answer a question. Coolcord has been pretty consistent in that regard.

**Comment by Coolcord** [comment]
Apologies W-Pangilinan, I have read your posts, but I haven't had much time to work on Level-Headed these days. Real life has been keeping me pretty busy.

This feature has actually been [requested before](https://github.com/Coolcord/Level-Headed/issues/7). While I like the idea, I'm simply lacking the man power to write it. If someone else wanted to write it, I would consider merging it in. However, with what little time I get to work on this project these days, I think my time would be better spent elsewhere. Specifically, the level generator overhaul needs to the top priority right now.

I apologize if this is disappointing, but as always, thanks for the interest in Level-Headed!
