### ISSUE TITLE
Tower RE music sounds so empty

### ISSUE THREAD

**Issue by GooSee2001** [Coolcord/Level-Headed#31]
Certain instruments in Tower RE music are empty.

**Comment by Coolcord** [comment]
Thanks for the feedback, and sorry for the late response!

That's true, not every instrument is used. However, I don't have time to spruce it up on my own. However, if you or someone else would like to add more to it, feel free! I'll include that patch in here if someone wants to contribute it.

I'm personally shifting focus of this project back to the level generator to prevent further feature creep.
