### ISSUE TITLE
Pipe Exits in Underground and Underwater Levels

### ISSUE THREAD

**Issue by ShatteredOverlord** [Coolcord/Level-Headed#33]
When in an underground / underwater level there is no pipe to go back to the overworld then get the flag. Instead the flags are just underground / underwater which never happens in the real game. It should be pretty easy to implement this as the overworld flag sections are all the same.

**Comment by Coolcord** [comment]
Thanks for the feedback! This has been addressed and will be released in the next update! Underground and underwater levels now always end with a pipe. 2 of the scrapped level slots have been repurposed as level endings to handle both small and large castles.

Auto scrolling levels will now also end in a pipe to prevent soft locks with scrolling the screen too far to the right and hitting the flagpole too soon.
