### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by ShatteredOverlord** [Coolcord/Level-Headed#34]
Is this project dead? It's been ages since the last update and the creator of this project is inactive. If it is discontinued it really is a shame.

**Comment by Coolcord** [comment]
Hi, thanks for the interest! It's always good to hear that people still enjoy Level-Headed!

I wouldn't call this project dead. More like on a long hiatus. My personal life has been very busy the past few years, so I haven't had much time to work on a hobby project in a while.

The source code does contain a few fixes that I never got around to releasing. If you compile from source, you can take advantage of these bug fixes. Take a look [here](https://github.com/Coolcord/Level-Headed/wiki/Compiling-Level%E2%80%90Headed-via-the-Unix-Build-Script) for more info on how to do that.

I apologize that I have no news on this after so long. If my personal life ever slows down again, I'll work on it. Unfortunately, that is the nature of hobby projects like these -- I'm the only one working on it and I don't get paid for doing so. Luckily, the project is open source if anyone wants to pick it up or contribute to it.

**Comment by ShatteredOverlord** [comment]
Thank you very much! I wasn't expecting a response. I understand how your
personal life can make you very busy but in the end do whatever you want. I
do hope you go back to the project one day but afterall it is your choice.

**Comment by ShatteredOverlord** [comment]
I really do hope you're doing alright. You are very talented and I love
your projects although I have no knowledge of any coding.

**Comment by Coolcord** [comment]
Thanks a lot for the encouragement! I appreciate the kind words! I've been good, just very busy with my personal life. Nothing bad.

I just released a new (small) update. I'm continuing work on this project, and I'm working on adding to the level generator, so expect more updates here soon.
