### ISSUE TITLE
[Feature Request] Preview Music / Graphics before generating

### ISSUE THREAD

**Issue by ghost** [Coolcord/Level-Headed#7]
I think this would be a nice addition so I don't have to generate a game to manually check each and every one.

**Comment by Coolcord** [comment]
I'll consider this, but it probably won't happen for a long time. I like the idea, but unfortunately, I think my time should be spent elsewhere in this project right now. However, if someone else wanted to write it, I wouldn't mind merging it in.

Thanks anyway for the suggestion!
